site/base_site/urls.py
"""testParseExample URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^textparser/', include('textparser.urls', namespace='textparser')),
]

site/core/urls.py
"""urls.py for core app

Author: James Hohman
Copyright James Hohman 2015
"""

from django.conf.urls import patterns, url


urlpatterns = patterns(
    'core.views',
    url(r'^$', 'index', name='index'),
    )

site/textparser/urls.py
"""urls.py for textparser app

Author: James Hohman
Copyright James Hohman 2015
"""

from django.conf.urls import patterns, url


urlpatterns = patterns(
    'textparser.views',
    url(r'^$', 'index', name='index'),
    url(r'^results/$', 'results', name='results'),
    url(r'^flush/$', 'flush', name='flush'),
    )

site/textparser/models.py
"""models.py for textparser app

Author: James Hohman
Copyright James Hohman 2015
"""
from django.db import models
from django.core.exceptions import ValidationError
from textparser.validators import IsAlphaValidator  # @UnresolvedImport


class WordManager(models.Manager):
    def get_or_create(self, *args, **kwargs):
        '''Custom get or create. On validation error returns the object
        but did not create it in db, with value of 0.'''
        created = False
        try:
            obj = Word.objects.get(**kwargs)
        except Word.DoesNotExist:
            obj = Word(**kwargs)
            try:
                obj.full_clean()
            except ValidationError:
                return obj, created
            obj.save()
            created = True

        return obj, created


class Letter(models.Model):
    letter = models.CharField(max_length=1, unique=True)
    value = models.IntegerField()

    def __unicode__(self):
        return self.letter


class Word(models.Model):
    '''The Word model. The longest English word is something like 28-45
    characters long depending how you qualify. Regardless, if it's longer than
    max_length we'll consider the value to be 0 and we won't store it.
    http://en.wikipedia.org/wiki/Longest_word_in_English
    '''
    word = models.CharField(
        max_length=64, unique=True, validators=[IsAlphaValidator])
    value = models.IntegerField(default=0, editable=False)

    objects = WordManager()

    def calcWordValue(self):
        '''Calculates the word value by querying each letter from the db.
        Yes, Letter.objects.all() should be cached somehow for
        performance reasons.'''
        letterQuery = Letter.objects.all()
        value = 0
        for l in self.word:
            try:
                value += letterQuery.get(letter=l).value
            except Letter.DoesNotExist:
                continue

        return value

    def validWord(self):
        '''Based on word length and numeric characters,
        is the word valid or not?'''
        if len(self.word) > 64:
            return False
        elif not self.word.isalpha():
            return False
        else:
            return True

    def save(self, *args, **kwargs):
        '''Calculate the value and save the word.'''
        self.word = self.word.lower()
        self.value = self.calcWordValue()
        super(Word, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.word

site/textparser/forms.py
"""forms.py for textparser app.

Author: James Hohman
Copyright James Hohman 2015
"""

from django import forms


class TextForm(forms.Form):
    text = forms.CharField(
        label='Input Text', max_length=10000, widget=forms.Textarea(
            attrs={'placeholder': 'Enter text here.',
                   'class': 'form-control required', 'rows': '5'}
            ))

site/core/views.py
"""views.py for core app

Author: James Hohman
Copyright James Hohman 2015
"""
from django.shortcuts import render


def index(request):
    resp_page = 'core/index.html'
    rc = {}

    results = request.session.get('result')
    if results is None:
        rc['hide_result_link'] = True

    return render(request, resp_page, rc)

site/textparser/views.py
"""views.py for textparser app

Author: James Hohman
Copyright James Hohman 2015
"""
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from textparser.forms import TextForm  # @UnresolvedImport
import json
from textparser.library import (
    parseText, removeStopWords  # @UnresolvedImport
    )


@csrf_protect
def index(request):
    '''Textparser index view. Presents text form on GET. Processes
    text form on POST.'''
    resp_page = 'textparser/index.html'
    rc = {}  # response context.

    if request.method == 'GET':
        results = request.session.get('result')
        if results is None:
            rc['hide_result_link'] = True
            textForm = TextForm()
        else:
            textForm = TextForm(initial={'text': request.session.get('text')})
    elif request.method == 'POST':
        textForm = TextForm(request.POST)
        counter = parseText(request, textForm.data.get('text'))
        removeStopWords(request, counter)
        return HttpResponseRedirect(reverse('textparser:results'))
    else:
        raise PermissionDenied

    rc['form'] = textForm

    return render(request, resp_page, rc)


def results(request):
    '''Textparser results view.'''
    resp_page = 'textparser/result.html'
    rc = {}  # response context.
    result = request.session.get('result')

    # We can clean up these dicts as necessary.
    # Here for the prototype.
    rc['jsonMetrics'] = json.dumps(result['metrics'])
    rc['jsonFreq'] = result['data']
    rc['jsonTop'] = result['top']
    rc['jsonTot'] = result['total']
    rc['jsonUniq'] = result['unique']
    rc['jsonRFreq'] = result['rdata']
    rc['jsonRTot'] = result['rtotal']
    rc['jsonRUniq'] = result['runique']

    return render(request, resp_page, rc)


@csrf_protect
def flush(request):
    '''Flushes the current session.'''
    if request.method != 'POST':
        raise PermissionDenied

    try:
        request.session.flush()
        messages.success(request,
                         "Success! Your session data has been flushed."
                         )
    except:
        messages.success(request,
                         "An error occurred while flushing session data."
                         )

    return HttpResponseRedirect(reverse('textparser:index'))

site/core/templates/common/d3_logo.html
<h1>
  <svg id="d3-logo" width="96" height="91" style="position:relative;top:22px;">
    <linearGradient id="logo-gradient-1" gradientUnits="userSpaceOnUse" x1="37.2417" y1="7.0552" x2="97.9669" y2="67.7803">
      <stop offset="0" stop-color="#F9A03C"/>
      <stop offset="1" stop-color="#F7974E"/>
    </linearGradient>
    <linearGradient id="logo-gradient-2" gradientUnits="userSpaceOnUse" x1="-8.0391" y1="17.2148" x2="45.724" y2="70.978">
      <stop offset="0" stop-color="#F9A03C"/>
      <stop offset="1" stop-color="#F7974E"/>
    </linearGradient>
    <linearGradient id="logo-gradient-3" gradientUnits="userSpaceOnUse" x1="11.9321" y1="36.5513" x2="66.3901" y2="91.0092">
      <stop offset="0" stop-color="#F9A03C"/>
      <stop offset="1" stop-color="#F7974E"/>
    </linearGradient>
    <linearGradient id="logo-gradient-4" gradientUnits="userSpaceOnUse" x1="1.6533" y1="-1.6533" x2="86.899" y2="83.5924">
      <stop offset="0" stop-color="#F26D58"/>
      <stop offset="1" stop-color="#F9A03C"/>
    </linearGradient>
    <linearGradient id="logo-gradient-5" gradientUnits="userSpaceOnUse" x1="45.2446" y1="-9.5483" x2="108.0998" y2="53.3068">
      <stop offset="0" stop-color="#B84E51"/>
      <stop offset="1" stop-color="#F68E48"/>
    </linearGradient>
    <linearGradient id="logo-gradient-6" gradientUnits="userSpaceOnUse" x1="6.6323" y1="64.3193" x2="49.6788" y2="107.3658">
      <stop offset="0" stop-color="#F9A03C"/>
      <stop offset="1" stop-color="#F7974E"/>
    </linearGradient>
    <path fill="url(#logo-gradient-1)" d="M95.82,65.857c0.043-0.418,0.074-0.84,0.098-1.264c0.029-0.502-30.211-29.194-30.211-29.194h-0.723C64.984,35.399,95.635,67.73,95.82,65.857z"/>
    <path fill="url(#logo-gradient-2)" d="M31.302,55.904c-0.04,0.088-0.08,0.176-0.121,0.264c-0.043,0.092-0.087,0.184-0.131,0.275c-0.964,2.01,13.495,16.145,14.658,14.428c0.053-0.076,0.106-0.156,0.159-0.232c0.059-0.09,0.117-0.176,0.175-0.266C46.972,68.961,31.715,54.986,31.302,55.904z"/>
    <path fill="url(#logo-gradient-3)" d="M51.734,75.781c-0.041,0.09-0.332,0.582-0.598,0.842c-0.045,0.09,14.115,14.133,14.115,14.133h1.275C66.527,90.756,53.234,76.375,51.734,75.781z"/>
    <path fill="url(#logo-gradient-4)" d="M95.938,64.338c-0.662,14.68-12.807,26.418-27.645,26.418h-2.006L51.469,76.158c1.219-1.719,2.352-3.5,3.361-5.357h13.463c4.258,0,7.723-3.463,7.723-7.723c0-4.258-3.465-7.723-7.723-7.723h-7.967c0.607-3.209,0.939-6.518,0.939-9.903c0-3.437-0.338-6.793-0.967-10.053h4.949l30.604,30.155C95.887,65.15,95.916,64.746,95.938,64.338z M8.05,0H0v19.955h8.05c14.06,0,25.5,11.437,25.5,25.497c0,3.825-0.853,7.456-2.369,10.716l14.686,14.471c4.822-7.215,7.641-15.877,7.641-25.187C53.508,20.39,33.115,0,8.05,0z"/>
    <path fill="url(#logo-gradient-5)" d="M68.293,0H35.695c7.962,4.861,14.555,11.754,19.047,19.955h13.551c4.258,0,7.723,3.463,7.723,7.723c0,4.259-3.465,7.722-7.723,7.722h-3.045l30.604,30.155c0.072-0.818,0.117-1.641,0.117-2.477c0-6.727-2.414-12.898-6.422-17.701c4.008-4.801,6.422-10.973,6.422-17.699C95.969,12.417,83.555,0,68.293,0z"/>
    <path fill="url(#logo-gradient-6)" d="M66.287,90.756H35.928C42.039,86.982,47.322,82,51.469,76.158L66.287,90.756z M45.867,70.639L31.182,56.168C27.125,64.887,18.284,70.951,8.05,70.951H0v19.953h8.05C23.804,90.904,37.709,82.846,45.867,70.639z"/>
  </svg>
  Data-Driven Documents
</h1>

site/core/templates/common/messages.html
{% if messages %}
<div class="messages">
  {% for message in messages %}
    {% if message.tags %}
      {% if message.tags == 'error' %}
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
          <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
      {% elif message.tags == 'success' %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade in" role="alert">
          <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <span class="sr-only">{{ message.tags }}:</span>
      {% else %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade in" role="alert">
          <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
          <span class="sr-only">Information:</span>
      {% endif %}
    {% else %}
      <div class="alert alert-info alert-dismissible fade in" role="alert">
        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
        <span class="sr-only">Information:</span>
    {% endif %}
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
</div>
{% endif %}

site/core/templates/core/index.html
{% extends "common/site_base.html" %}

{% block extrastyle %}
    <!-- unmodified cover.css -->
    <link href="{{ STATIC_URL }}core/css/cover.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ STATIC_URL }}core/css/index.css" rel="stylesheet">
{% endblock %}

{% block body %}
    <body style="background: transparent url({{ STATIC_URL }}common/img/{{ siteParams.background }}) no-repeat center center fixed;">
    <!-- Bootstrap cover example -->
    <!-- http://getbootstrap.com/examples/cover/ -->
    <!-- Modified for this example site by James Hohman, 2015. -->
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">{{ siteParams.title }}</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="{% url 'core:index' %}">Home</a></li>
                  <li><a href="{% url 'textparser:index' %}">TextParser</a></li>
                  {% if not hide_result_link %}
                    <li><a href="{% url 'textparser:results' %}">Results</a>
                  {% endif %}
                  <!--<li><a href="#">Contact</a></li>-->
                </ul>
              </nav>
            </div>
          </div>
          <div class="inner cover first-cover">
            <h1 class="cover-heading">Text and d3.js Visualizations</h1>
            <p class="lead">This Django powered website provides an example
            of how to perform some <a href="http://d3js.org/">d3.js</a>
            visualizations using <a href="https://www.python.org/"
            >Python</a>/<a href="https://www.djangoproject.com/">Django</a>,
            <a href="http://en.wikipedia.org/wiki/JavaScript">JavaScript</a>,
            and <a href="https://jquery.com/">jQuery</a>. The site follows
            responsive design principles courtesy of the
            <a href="http://getbootstrap.com/">Bootstrap</a> Framework.</p>
            <p class="lead">
              <a href="{% url 'textparser:index' %}" class="btn btn-lg btn-default">TextParser</a>
            </p>
          </div>
          <div class="inner cover">
            <h1 class="cover-heading">Bootstrap, for responsive design.</h1>
            <p class="lead"><img class="third-party-logo"
              src="{{ STATIC_URL }}common/img/bootstrap-solid.svg"></p>
            <p class="lead">
              <a href="http://getbootstrap.com/" class="btn btn-lg
              btn-default">Learn more</a>
            </p>
          </div>
          <div class="inner cover">
            <h1 class="cover-heading">Powered by Python</h1>
            <p class="lead"><img class="third-party-logo"
              src="{{ STATIC_URL }}common/img/python-logo-large.png"></p>
            <p class="lead">
              <a href="https://www.python.org/" class="btn btn-lg
              btn-default">Learn more</a>
            </p>
          </div>
          <div class="inner cover">
            <h1 class="cover-heading">Powered by</h1>
            <p class="lead"><img class="third-party-logo"
              src="{{ STATIC_URL }}common/img/logo-django.42234b631760.svg"></p>
            <p class="lead">
              <a href="https://www.djangoproject.com/"
              class="btn btn-lg btn-default">Learn more</a>
            </p>
          </div>
          <div class="inner cover">
            <h1 class="cover-heading">Powered by d3.js</h1>
            {% include 'common/d3_logo.html' %}
            <h1>&nbsp; </h1>
            <p class="lead">
              <a href="http://d3js.org/" class="btn btn-lg
              btn-default">Learn more</a>
            </p>
          </div>
          <div class="inner cover">
            <h1 class="cover-heading">Powered by</h1>
            <p class="lead"><img id="jquery-logo" class="third-party-logo"
              src="{{ STATIC_URL }}common/img/jQuery-logo.PNG"></p>
            <p class="lead">
              <a href="https://jquery.com/" class="btn btn-lg
              btn-default">Learn more</a>
            </p>
          </div>
          <div class="mastfoot">
            <div class="inner">
              <p> &copy; {{ siteParams.company|title }},
              {{ siteParams.current_year }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block footer %}{% endblock %}

{% block includeJS %}
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{ STATIC_URL }}core/js/ie10-viewport-bug-workaround.js"></script>
    <script src="{{ STATIC_URL }}core/js/cover.js"></script>
{% endblock %}

site/textparser/templates/textparser/index.html
{% extends "common/site_base.html" %}

{% block extrastyle %}
    <!-- unmodified cover.css -->
    <link href="{{ STATIC_URL }}core/css/cover.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ STATIC_URL }}core/css/index.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ STATIC_URL }}textparser/css/textparser.css"
    rel="stylesheet">
{% endblock %}

{% block body %}
  <body style="background: url({{ STATIC_URL }}common/img/{{ siteParams.background }}) no-repeat center center fixed;">
    <!-- Bootstrap cover example -->
    <!-- http://getbootstrap.com/examples/cover/ -->
    <!-- Modified for this example site by James Hohman, 2015. -->
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">{{ siteParams.title }}</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li><a href="{% url 'core:index' %}">Home</a></li>
                  <li class="active"><a href="{% url 'textparser:index' %}">
                  TextParser</a></li>
                  {% if not hide_result_link %}
                    <li><a href="{% url 'textparser:results' %}">Results</a>
                  {% endif %}
                  <!--<li><a href="#">Contact</a></li>-->
                </ul>
              </nav>
            </div>
          </div>
          {% include 'common/messages.html' %}
          <div class="inner cover form-group first-cover">
            <h1 class="cover-heading">TextParser</h1>
            {% comment %}
            <!--
            The following template loops allow for more granular control
            of form rendering. We display form errors as bootstrap
            dismissible alerts.
            -->
            {% endcomment %}
            <form action="{% url 'textparser:index' %}" method="post"
            id="textform">
              {% csrf_token %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                  {{ error }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
              {% for error in form.text.errors %}
                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                  {{ error }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
              {% for field in form %}
                {{ field }}
              {% endfor %}
              <!-- {{ form }} -->
              <p class="lead"></p>
              <p class="lead">
                <button class="btn btn-lg btn-default"  type="submit"
                form="textform" value="Submit">Submit</button>
              </p>
            </form>
          </div>
          <div class="mastfoot">
            <div class="inner">
              <p> &copy; {{ siteParams.company|title }},
              {{ siteParams.current_year }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block footer %}{% endblock %}

{% block includeJS %}
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="{{ STATIC_URL }}core/js/ie10-viewport-bug-workaround.js"></script>
  <script type="text/javascript">
    $('label[for=id_text]').addClass('sr-only');
  </script>
{% endblock %}

site/textparser/templates/textparser/result.html
{% extends "common/site_base.html" %}

{% block extrastyle %}
    <!-- unmodified cover.css -->
    <link href="{{ STATIC_URL }}core/css/cover.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ STATIC_URL }}core/css/index.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ STATIC_URL }}textparser/css/textparser.css"
    rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ STATIC_URL }}textparser/css/results.css"
    rel="stylesheet">
{% endblock %}

{% block body %}
  <body style="background: url({{ STATIC_URL }}common/img/{{ siteParams.background }}) no-repeat center center fixed;">
    <!-- Bootstrap cover example -->
    <!-- http://getbootstrap.com/examples/cover/ -->
    <!-- Modified for this example site by James Hohman, 2015. -->
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">{{ siteParams.title }}</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li><a href="{% url 'core:index' %}">Home</a></li>
                  <li><a href="{% url 'textparser:index' %}">
                  TextParser</a></li>
                  <li class="active"><a href="{% url 'textparser:results' %}">
                  Results</a></li>
                  <!--<li><a href="#">Contact</a></li>-->
                </ul>
              </nav>
            </div>
          </div>
          {% include 'common/messages.html' %}
          <div class="inner cover first-cover">
            <h1 class="cover-heading">Results</h1>
            <div class="panel panel-default">
              <ul class="nav nav-tabs">
                <li role="presentation" class="active"><a id="ctrl-table" href="javascript:void(0)" onclick="javascript:results.tabClick(this)">Table</a></li>
                <li role="presentation"><a id="ctrl-word-table" href="javascript:void(0)" onclick="javascript:results.tabClick(this)">Word List</a></li>
                <li role="presentation"><a id="ctrl-d3-score" href="javascript:void(0)" onclick="javascript:results.tabClick(this)">Scrabble<sup>TM</sup> Score</a></li>
                <li role="presentation"><a id="ctrl-d3-freq" href="javascript:void(0)" onclick="javascript:results.tabClick(this)">Frequency</a></li>
              </ul>
              <!-- <div> -->
              <!-- Default panel heading -->
              <div id="result-heading" class="panel-heading">Result Table</div>
              <!-- Default panel details -->
              <div id="result-body" class="panel-body" style="display: none;"><p></p></div>
              <div id="result-table" class="panel-body">
                <!-- This is a temporary patch until I can fix this layout
                  properly. There should not be 2 panel-bodies. -->
                <!-- Table -->
                <table class="table result-table">
                  <thead>
                    <tr>
                      <th>Metric</th>
                      <th>Count</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>Total words (Raw)</td>
                      <td>{{ jsonRTot }}</td>
                    </tr>
                    <tr>
                      <td>Total words</td>
                      <td>{{ jsonTot }}</td>
                    </tr>
                    <tr>
                      <td>Unique words (Raw)</td>
                      <td>{{ jsonRUniq }}</td>
                    </tr>
                    <tr>
                      <td>Unique words</td>
                      <td>{{ jsonUniq }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div id="result-word-table" class="panel-body" style="display: none;">
                <!-- This is a temporary patch until I can fix this layout
                  properly. There should not be 2 panel-bodies. -->
                <p class="lead">Top Words</p>
                <!-- Table -->
                <table id="list-table" class="table result-table">
                  <thead>
                    <tr>
                      <th>Rank</th>
                      <th>Word</th>
                      <th>Frequency</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for words in jsonTop %}
                    <tr>
                      <td>{{ forloop.counter }}</td>
                      <td>{{ words.0 }}</td>
                      <td>{{ words.1 }}</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
                <p class="lead">All Words</p>
                <!-- Table -->
                <table id="all-table" class="table result-table">
                  <thead>
                    <tr>
                      <th>Rank</th>
                      <th>Word</th>
                      <th>Frequency</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for words in jsonFreq %}
                    <tr>
                      <td>{{ forloop.counter }}</td>
                      <td>{{ words.0 }}</td>
                      <td>{{ words.1 }}</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
              <div id="result-footer" class="panel-footer">
                <form action="{% url 'textparser:flush' %}" method="post">
                  {% csrf_token %}
                  <input type="submit" class="btn btn-md btn-info"
                  value="Clear Results">
                </form>
              </div>
            <!-- </div> -->
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p> &copy; {{ siteParams.company|title }},
              {{ siteParams.current_year }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block footer %}{% endblock %}

{% block includeJS %}
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="{{ STATIC_URL }}core/js/ie10-viewport-bug-workaround.js"></script>
  <!-- d3.js Stuff -->
  {% if siteParams.cdn %}<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
  {% else %}<script src="{{ STATIC_URL }}d3-v3.5.5/d3-v3.5.5.min.js"></script>{% endif %}
  <script src="{{ STATIC_URL }}throttle.js/jquery.ba-throttle-debounce.min.js" type="text/javascript"></script>
  <!-- results.js controls interface -->
  <script src="{{ STATIC_URL }}textparser/js/results.js"></script>
  <!-- results.js controls interface -->
  {% if jsonMetrics %}
  <script type="text/javascript">
    $(document).ready(function() {
      results.jsonLoad({{ jsonMetrics|safe|default_if_none:'{"key": "error", "value": "no json data."}'|default:'{"key": "error", "value": "no json data."}' }}, {{ jsonParams|safe|default_if_none:'{"key": "info", "value": "no chart parameters."}'|default:'{"key": "info", "value": "no chart parameters."}' }});
    });
  </script>
  <!-- Bar Chart Stuff -->
  <script src="{{ STATIC_URL }}textparser/js/d3_bar_chart.js"></script>
  <!-- End Bar Chart Stuff -->
  <!-- Scrabble Chart Stuff -->
  <script src="{{ STATIC_URL }}textparser/js/d3_forced_layout_chart.js"></script>
  <!-- End Scrabble Chart Stuff -->
  {% endif %}
{% endblock %}